# Generated by Django 5.1 on 2025-09-03 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.IntegerField()),
                ('action', models.CharField(choices=[('IN', 'Dentro del rango'), ('OUT', 'Fuera del rango')], max_length=3)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.BooleanField(default=True)),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.baliza')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('state', models.BooleanField(default=True)),
                ('baliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='api.baliza')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='api.sala')),
            ],
        ),
    ]
