# Generated by Django 5.1 on 2025-02-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='dueño',
            new_name='owner',
        ),
    ]
