# Generated by Django 5.1 on 2025-02-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_dueño_nota_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
