# Generated by Django 5.1.3 on 2025-08-31 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('IN', 'Dentro del rango'), ('OUT', 'Fuera del rango')], max_length=3)),
                ('fecha', models.DateTimeField()),
                ('baliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='contador.baliza')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='contador.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('baliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='contador.baliza')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='contador.sala')),
            ],
        ),
    ]
