# Generated by Django 5.1 on 2025-08-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baliza',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
