# Generated by Django 5.1.5 on 2025-01-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(max_length=255, verbose_name='Apellido del Autor'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombres',
            field=models.CharField(max_length=255, verbose_name='Nombres del Autor'),
        ),
    ]
