# Generated by Django 5.1 on 2025-01-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
