# Generated by Django 5.1 on 2025-01-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idioma',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redesautor',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saga',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
