# Generated by Django 5.1 on 2025-01-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_autor_state_categoria_state_editorial_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
