# Generated by Django 5.1 on 2025-01-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_imagenes_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='descripcion',
        ),
    ]
