# Generated by Django 5.1 on 2025-01-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_remove_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='saga',
        ),
        migrations.DeleteModel(
            name='Saga',
        ),
    ]
