# Generated by Django 5.1 on 2025-01-24 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_categoryproduct_measure_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='categry_product',
            new_name='category_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categry_product',
            new_name='category_product',
        ),
    ]
